basePath: /api
definitions:
  model.HealthResp:
    properties:
      status:
        type: string
    type: object
  model.TagsResp:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8088
info:
  contact:
    email: support@swagger.io
    name: zang
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 健康检查
      produces:
      - application/json
      responses:
        "200":
          description: 健康检查成功
          schema:
            $ref: '#/definitions/model.HealthResp'
      summary: 健康检查
      tags:
      - health
  /tag/:id:
    get:
      description: 根据id获取tag
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功获取tag
          schema:
            $ref: '#/definitions/model.TagsResp'
      summary: 根据id获取tag
      tags:
      - GetTagById
swagger: "2.0"
